apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }} 
  namespace:  {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.label }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http{{ .Values.service.port }} 
  selector:
    app: {{ .Values.service.selector }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-myservicea
  namespace:  {{ .Values.metadata.namespace }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.service.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.metadata.name }}
          servicePort: {{ .Values.service.port }}
