apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.7
apiServer:
  certSANs:
  - "172.16.13.54"
networking:
  podSubnet: 192.168.0.0/16
controlPlaneEndpoint: "172.16.13.54:6443"
imageRepository: gcr.azk8s.cn/google_containers
