apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claimceph
  labels:
    app: wordpressceph
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
