apiVersion: v1
kind: List
items:  
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: dev2
      labels:
        name: dev2
      namespace: dev
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: dev2
      namespace: dev
      labels:
        name: dev2
    roleRef:
      kind: ClusterRole
      name: admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: dev2
        namespace: dev
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: dev2
      namespace: test
      labels:
        name: dev2
    roleRef:
      kind: ClusterRole
      name: admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: dev2
        namespace: dev
  - apiVersion: rbac.authorization.k8s.io/v1beta1
    kind: RoleBinding
    metadata:
      name: dev2
      namespace: pre
      labels:
        name: dev2
    roleRef:
      kind: ClusterRole
      name: admin
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: dev2
        namespace: dev
