kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gluster-heketi-external
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://172.16.13.54:18080"
  restuser: "admin"
  secretName: "heketi-secret"
  secretNamespace: "default"
  volumetype: "replicate:2"
allowVolumeExpansion: true
